Add new summary tab to dashboard
RuntimeTools/SwiftMetrics pull request #177
Opened 2018-01-09 13:50 UTC by sjanuary

Includes update to graphmetrics 1.1.0

2018-01-15 15:39 UTC, mattcolegate requested changes
Changes look good, pulled and tested - summary tab comes up fine with good-looking data, came across issue where if you maximise the Environment pane, switch to the Dashboard tab then back to the Summary tab, the Environment pane is no longer central.

2018-01-16 14:38 UTC, sjanuary commented
Fixed tab-switch bug in graphmetrics -https://github.com/RuntimeTools/graphmetrics/pull/46
Updated submodule again to point to latest graphmetrics

2018-01-16 14:46 UTC, mattcolegate approved these changes

2018-01-16 14:47 UTC, mattcolegate commented
Change to graphmetrics fixes behaviour previously seen. Change approved so long as Travis builds

2018-01-16 16:21 UTC, merged